version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "diplom_db"
      POSTGRES_USER: "diplom_user"
      POSTGRES_PASSWORD: "diplom_pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080